apiVersion: v1
kind: Service
metadata:
  namespace: kube-logging
  name: kibana
  labels:
    app: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    targetPort: 5601
    name: ui 
  selector:
    app: kibana 