apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: fluentd-sidecar
  ports:
    - protocol: TCP
      port: 8080  # Assuming your Tomcat application runs on port 8080
      targetPort: 8080
  type: LoadBalancer
