
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  namespace: kube-logging
parameters:
  type: gp2
  fsType: ext4 
provisioner: kubernetes.io/aws-ebs 
reclaimPolicy: Delete 
volumeBindingMode: WaitForFirstConsumer
allowedTopologies: 
- matchLabelExpressions: 
  - key: failure-domain.beta.kubernetes.io/zone
    values: 
    - eu-west-1b
    - eu-west-1c